<?php

/**
 * Do not edit this file unless you know what you're doing.
 */

/**
 * Helper function for prettying up errors.
 *
 * @param string $message
 * @param string $subtitle
 * @param string $title
 */
$sage_error = function ( $message, $subtitle = '', $title = '' ) {
	$title   = $title ?: __( 'Stage Child &rsaquo; Error', 'stage' );
	$message = "<h1>{$title}<br><small>{$subtitle}</small></h1><p>{$message}</p>";
	wp_die( $message, $title );
};

/**
 * Ensure the parent theme is available
 */
if ( ! wp_get_theme( 'stage' )->exists() ) {
	$sage_error( __( 'The Parent Theme Framework "Stage" is not available.', 'stage' ), __( 'Your Stage is Missing', 'stage' ) );
}

/**
 * Ensure dependencies are loaded.
 */
if ( ! file_exists( $composer = __DIR__ . '/vendor/autoload.php' ) ) {
	$sage_error(
		__( 'You must run <code>composer install</code> from the Stage directory.', 'stage' ),
		__( 'Autoloader not found.', 'stage' )
	);
}

require_once $composer;

/**
 * Register any Sage theme files.
 *
 * The mapped array determines the code library included in your theme.
 * Add or remove files to the array as needed. Supports child theme overrides.
 */
array_map(
	function ( $file ) use ( $sage_error ) {
		$file = "app/{$file}.php";
		if ( ! locate_template( $file, true, true ) ) {
			$sage_error(
				sprintf(
					/* translators: %s is replaced with the missing file path. */
					__( 'Error locating <code>%s</code> for inclusion.', 'stage' ),
					$file
				),
				__( 'File not found', 'stage' )
			);
		}
	},
	array( 'helpers', 'setup', 'filters', 'admin' )
);

/**
 * Boot Acorn with the Sage provider.
 *
 * @link https://roots.io/acorn/
 */
add_theme_support( 'sage' );
Roots\bootloader();
